import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Customer Auth",
  description: "Generated by create next app",
};


interface AuthLayoutProps {
  children: React.ReactNode;
  maxWidth?: string;
}

export default function AuthLayout({ children, maxWidth = "max-w-4xl" }: AuthLayoutProps) {
  return (
    <div className="min-h-screen bg-gray-100 flex flex-col items-center justify-center p-4">
      <div className={`w-full ${maxWidth} bg-white shadow-2xl rounded-2xl overflow-hidden relative`}>
        <div className="mt-4">{children}</div>
      </div>
    </div>
  );
}