import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Customer Auth",
  description: "Generated by create next app",
};

interface AuthLayoutProps {
  children: React.ReactNode;
}

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        style={{ backgroundImage: 'url(https://www.originfitness.com/media/magefan_blog/Dollar_Academy_WEB-01.jpg)' }}    
      >
        {/* Centered Content */}
        <div className="min-h-screen flex flex-col items-center justify-center relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}